declare module 'three' {
  export = THREE;
  export as namespace THREE;
  namespace THREE {
    // Basic types needed for vanta
    export const Scene: any;
    export const Camera: any;
    export const WebGLRenderer: any;
    export const Mesh: any;
    export const Geometry: any;
    export const Material: any;
    export const Light: any;
    export const Object3D: any;
    export const Vector3: any;
    export const Color: any;
    export const Texture: any;
    export const Loader: any;
    export const BufferGeometry: any;
    export const ShaderMaterial: any;
    export const Group: any;
    export const PerspectiveCamera: any;
    export const OrthographicCamera: any;
    export const DirectionalLight: any;
    export const AmbientLight: any;
    export const PointLight: any;
    export const SpotLight: any;
    export const HemisphereLight: any;
    export const LightShadow: any;
    export const CameraHelper: any;
    export const Box3: any;
    export const Box3Helper: any;
    export const PlaneGeometry: any;
    export const BoxGeometry: any;
    export const SphereGeometry: any;
    export const CylinderGeometry: any;
    export const MeshBasicMaterial: any;
    export const MeshLambertMaterial: any;
    export const MeshPhongMaterial: any;
    export const MeshStandardMaterial: any;
    export const MeshPhysicalMaterial: any;
    export const LineBasicMaterial: any;
    export const LineDashedMaterial: any;
    export const PointsMaterial: any;
    export const SpriteMaterial: any;
    export const TextureLoader: any;
    export const ImageLoader: any;
    export const CubeTextureLoader: any;
    export const DataTexture: any;
    export const VideoTexture: any;
    export const CompressedTexture: any;
    export const CanvasTexture: any;
    export const DepthTexture: any;
    export const Clock: any;
    export const AnimationMixer: any;
    export const KeyframeTrack: any;
    export const PropertyBinding: any;
    export const PropertyMixer: any;
    export const BooleanKeyframeTrack: any;
    export const ColorKeyframeTrack: any;
    export const NumberKeyframeTrack: any;
    export const QuaternionKeyframeTrack: any;
    export const StringKeyframeTrack: any;
    export const VectorKeyframeTrack: any;
    export const AnimationClip: any;
    export const AnimationAction: any;
    export const AnimationObjectGroup: any;
    export const AnimationUtils: any;
    export const KeyframeTrackConstructor: any;
    export const KeyframeTrackPrototype: any;
    export const REVISION: string;
    export const MOUSE: any;
    export const CullFaceNone: any;
    export const CullFaceBack: any;
    export const CullFaceFront: any;
    export const CullFaceFrontBack: any;
    export const FrontFaceDirectionCW: any;
    export const FrontFaceDirectionCCW: any;
    export const BasicShadowMap: any;
    export const PCFShadowMap: any;
    export const PCFSoftShadowMap: any;
    export const VSMShadowMap: any;
    export const FrontSide: any;
    export const BackSide: any;
    export const DoubleSide: any;
    export const FlatShading: any;
    export const SmoothShading: any;
    export const NoColors: any;
    export const FaceColors: any;
    export const VertexColors: any;
    export const NoBlending: any;
    export const NormalBlending: any;
    export const AdditiveBlending: any;
    export const SubtractiveBlending: any;
    export const MultiplyBlending: any;
    export const CustomBlending: any;
    export const AddEquation: any;
    export const SubtractEquation: any;
    export const ReverseSubtractEquation: any;
    export const MinEquation: any;
    export const MaxEquation: any;
    export const ZeroFactor: any;
    export const OneFactor: any;
    export const SrcColorFactor: any;
    export const OneMinusSrcColorFactor: any;
    export const SrcAlphaFactor: any;
    export const OneMinusSrcAlphaFactor: any;
    export const DstAlphaFactor: any;
    export const OneMinusDstAlphaFactor: any;
    export const DstColorFactor: any;
    export const OneMinusDstColorFactor: any;
    export const SrcAlphaSaturateFactor: any;
    export const NeverDepth: any;
    export const AlwaysDepth: any;
    export const LessDepth: any;
    export const LessEqualDepth: any;
    export const EqualDepth: any;
    export const GreaterEqualDepth: any;
    export const GreaterDepth: any;
    export const NotEqualDepth: any;
    export const MultiplyOperation: any;
    export const MixOperation: any;
    export const AddOperation: any;
    export const NoToneMapping: any;
    export const LinearToneMapping: any;
    export const ReinhardToneMapping: any;
    export const Uncharted2ToneMapping: any;
    export const CineonToneMapping: any;
    export const ACESFilmicToneMapping: any;
    export const UVMapping: any;
    export const CubeReflectionMapping: any;
    export const CubeRefractionMapping: any;
    export const EquirectangularReflectionMapping: any;
    export const EquirectangularRefractionMapping: any;
    export const SphericalReflectionMapping: any;
    export const CubeUVReflectionMapping: any;
    export const CubeUVRefractionMapping: any;
    export const RepeatWrapping: any;
    export const ClampToEdgeWrapping: any;
    export const MirroredRepeatWrapping: any;
    export const NearestFilter: any;
    export const NearestMipMapNearestFilter: any;
    export const NearestMipMapLinearFilter: any;
    export const LinearFilter: any;
    export const LinearMipMapNearestFilter: any;
    export const LinearMipMapLinearFilter: any;
    export const UnsignedByteType: any;
    export const ByteType: any;
    export const ShortType: any;
    export const UnsignedShortType: any;
    export const IntType: any;
    export const UnsignedIntType: any;
    export const FloatType: any;
    export const HalfFloatType: any;
    export const UnsignedShort4444Type: any;
    export const UnsignedShort5551Type: any;
    export const UnsignedShort565Type: any;
    export const UnsignedInt248Type: any;
    export const AlphaFormat: any;
    export const RGBFormat: any;
    export const RGBAFormat: any;
    export const LuminanceFormat: any;
    export const LuminanceAlphaFormat: any;
    export const RGBEFormat: any;
    export const DepthFormat: any;
    export const DepthStencilFormat: any;
    export const RGB_S3TC_DXT1_Format: any;
    export const RGBA_S3TC_DXT1_Format: any;
    export const RGBA_S3TC_DXT3_Format: any;
    export const RGBA_S3TC_DXT5_Format: any;
    export const RGB_PVRTC_4BPPV1_Format: any;
    export const RGB_PVRTC_2BPPV1_Format: any;
    export const RGBA_PVRTC_4BPPV1_Format: any;
    export const RGBA_PVRTC_2BPPV1_Format: any;
    export const RGB_ETC1_Format: any;
    export const RGBA_ASTC_4x4_Format: any;
    export const RGBA_ASTC_5x4_Format: any;
    export const RGBA_ASTC_5x5_Format: any;
    export const RGBA_ASTC_6x5_Format: any;
    export const RGBA_ASTC_6x6_Format: any;
    export const RGBA_ASTC_8x5_Format: any;
    export const RGBA_ASTC_8x6_Format: any;
    export const RGBA_ASTC_8x8_Format: any;
    export const RGBA_ASTC_10x5_Format: any;
    export const RGBA_ASTC_10x6_Format: any;
    export const RGBA_ASTC_10x8_Format: any;
    export const RGBA_ASTC_10x10_Format: any;
    export const RGBA_ASTC_12x10_Format: any;
    export const RGBA_ASTC_12x12_Format: any;
    export const LoopOnce: any;
    export const LoopRepeat: any;
    export const LoopPingPong: any;
    export const InterpolateDiscrete: any;
    export const InterpolateLinear: any;
    export const InterpolateSmooth: any;
    export const ZeroCurvatureEnding: any;
    export const ZeroSlopeEnding: any;
    export const WrapAroundEnding: any;
    export const TrianglesDrawMode: any;
    export const TriangleStripDrawMode: any;
    export const TriangleFanDrawMode: any;
    export const LinearEncoding: any;
    export const sRGBEncoding: any;
    export const GammaEncoding: any;
    export const RGBEEncoding: any;
    export const LogLuvEncoding: any;
    export const RGBM7Encoding: any;
    export const RGBM16Encoding: any;
    export const RGBDEncoding: any;
    export const BasicDepthPacking: any;
    export const RGBADepthPacking: any;
  }
}

declare module 'vanta/dist/vanta.fog.min' {
  interface VantaEffect {
    destroy(): void;
  }

  interface VantaOptions {
    el: HTMLElement;
    THREE: any;
    mouseControls?: boolean;
    touchControls?: boolean;
    gyroControls?: boolean;
    minHeight?: number;
    minWidth?: number;
    highlightColor?: number;
    midtoneColor?: number;
    lowlightColor?: number;
    baseColor?: number;
    blurFactor?: number;
    speed?: number;
    zoom?: number;
  }

  function FOG(options: VantaOptions): VantaEffect;
  export default FOG;
}